USE QUANLYCHUCVU_B3_MSSV 
GO
--------------------
DELETE TAMUNG
DELETE BANGCHAMCONG
DELETE LUONGTHANG
DELETE NV_CHUCVU
DELETE PHUCAPKHAC
DELETE PHUCAPCV
DELETE NHANVIEN
DELETE PHONGBAN


DROP TABLE  TAMUNG
DROP TABLE  BANGCHAMCONG
DROP TABLE  LUONGTHANG
DROP TABLE  NV_CHUCVU
DROP TABLE  PHUCAPKHAC
DROP TABLE  PHUCAPCV
DROP TABLE  NHANVIEN
DROP TABLE  PHONGBAN


USE MASTER
GO 
DROP DATABASE QUANLYCHUCVU_B3_MSSV

