USE QUANLYCHUCVU_B3_207ct55065 
-------------------------------
GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (1, 1, 2009, 24)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (1, 2, 2009, 23)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (1, 3, 2009, 22)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (1, 4, 2009, 21)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (2, 1, 2008, 24)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (2, 2, 2008, 19)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (2, 3, 2009, 23)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (2, 4, 2009, 12)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (3, 1, 2009, 23)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (3, 2, 2009, 22)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (3, 3, 2009, 19)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (3, 4, 2009, 24)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (4, 1, 2009, 24)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (4, 2, 2009, 22)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (4, 3, 2009, 24)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (4, 4, 2009, 22)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (5, 1, 2009, 24)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (5, 2, 2009, 22)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (5, 3, 2009, 21)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (5, 4, 2009, 24)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (6, 1, 2009, 23)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (6, 2, 2009, 24)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (6, 3, 2009, 21)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (6, 4, 2009, 4)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (7, 1, 2009, 24)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (7, 2, 2009, 19)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (7, 3, 2009, 23)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (7, 4, 2009, 21)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (8, 1, 2009, 24)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (8, 2, 2009, 21)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (8, 3, 2009, 24)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (8, 4, 2009, 21)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (9, 1, 2009, 23)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (9, 2, 2009, 21)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (9, 3, 2009, 24)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (9, 4, 2009, 23)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (10, 1, 2009, 24)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (10, 2, 2009, 21)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (10, 3, 2009, 19)

GO
INSERT INTO [dbo].[BANGCHAMCONG] ([MSNV], [THANG], [NAM], [SONGAYCONG])
	VALUES (10, 4, 2009, 5)

GO

--Table dbo.LUONGTHANG

INSERT INTO [dbo].[LUONGTHANG] ([MSNV], [THANG], [NAM], [LUONGCB], [TAMUNG], [PHUCAP], [TONGLUONG])
	VALUES (1, 1, 2009, 7000000, 200000, 200000, 7000000)

GO
INSERT INTO [dbo].[LUONGTHANG] ([MSNV], [THANG], [NAM], [LUONGCB], [TAMUNG], [PHUCAP], [TONGLUONG])
	VALUES (1, 2, 2009, 7000000, 200000, 450000, 7250000)

GO
INSERT INTO [dbo].[LUONGTHANG] ([MSNV], [THANG], [NAM], [LUONGCB], [TAMUNG], [PHUCAP], [TONGLUONG])
	VALUES (3, 1, 2009, 5000000, 200000, 500000, 5300000)

GO
INSERT INTO [dbo].[LUONGTHANG] ([MSNV], [THANG], [NAM], [LUONGCB], [TAMUNG], [PHUCAP], [TONGLUONG])
	VALUES (5, 1, 2009, 4500000, 0, 600000, 5100000)

GO

--Table dbo.NHANVIEN

INSERT INTO [dbo].[NHANVIEN] ([MSNV], [HOTEN], [MAPB], [LOAINV], [TRANGTHAI])
	VALUES (1, N'Pham Hoang Tu', 1, N'NV', N'Y')

GO
INSERT INTO [dbo].[NHANVIEN] ([MSNV], [HOTEN], [MAPB], [LOAINV], [TRANGTHAI])
	VALUES (2, N'To Thi Tuong Vi', 1, N'CH', N'N')

GO
INSERT INTO [dbo].[NHANVIEN] ([MSNV], [HOTEN], [MAPB], [LOAINV], [TRANGTHAI])
	VALUES (3, N'Dang Chi Thanh', 2, N'NV', N'Y')

GO
INSERT INTO [dbo].[NHANVIEN] ([MSNV], [HOTEN], [MAPB], [LOAINV], [TRANGTHAI])
	VALUES (4, N'Nguyen Mai Trang', 2, N'CH', N'Y')

GO
INSERT INTO [dbo].[NHANVIEN] ([MSNV], [HOTEN], [MAPB], [LOAINV], [TRANGTHAI])
	VALUES (5, N'Nguyen Do Thuy Lam', 3, N'NV', N'Y')

GO
INSERT INTO [dbo].[NHANVIEN] ([MSNV], [HOTEN], [MAPB], [LOAINV], [TRANGTHAI])
	VALUES (6, N'Nguyen Van Tung', 3, N'CH', N'N')

GO
INSERT INTO [dbo].[NHANVIEN] ([MSNV], [HOTEN], [MAPB], [LOAINV], [TRANGTHAI])
	VALUES (7, N'Nguyen Anh Thu', 4, N'NV', N'Y')

GO
INSERT INTO [dbo].[NHANVIEN] ([MSNV], [HOTEN], [MAPB], [LOAINV], [TRANGTHAI])
	VALUES (8, N'Do Ngoc Anh', 4, N'CH', N'Y')

GO
INSERT INTO [dbo].[NHANVIEN] ([MSNV], [HOTEN], [MAPB], [LOAINV], [TRANGTHAI])
	VALUES (9, N'Lam Bao Long', 5, N'NV', N'Y')

GO
INSERT INTO [dbo].[NHANVIEN] ([MSNV], [HOTEN], [MAPB], [LOAINV], [TRANGTHAI])
	VALUES (10, N'Nguyen Thanh Ngan', 5, N'CH', N'N')

GO

--Table dbo.NV_CHUCVU

INSERT INTO [dbo].[NV_CHUCVU] ([MSNV], [MSCV])
	VALUES (1, 1)

GO
INSERT INTO [dbo].[NV_CHUCVU] ([MSNV], [MSCV])
	VALUES (2, 2)

GO
INSERT INTO [dbo].[NV_CHUCVU] ([MSNV], [MSCV])
	VALUES (3, 3)

GO
INSERT INTO [dbo].[NV_CHUCVU] ([MSNV], [MSCV])
	VALUES (4, 5)

GO
INSERT INTO [dbo].[NV_CHUCVU] ([MSNV], [MSCV])
	VALUES (5, 4)

GO
INSERT INTO [dbo].[NV_CHUCVU] ([MSNV], [MSCV])
	VALUES (6, 1)

GO
INSERT INTO [dbo].[NV_CHUCVU] ([MSNV], [MSCV])
	VALUES (7, 4)

GO
INSERT INTO [dbo].[NV_CHUCVU] ([MSNV], [MSCV])
	VALUES (8, 5)

GO
INSERT INTO [dbo].[NV_CHUCVU] ([MSNV], [MSCV])
	VALUES (9, 2)

GO
INSERT INTO [dbo].[NV_CHUCVU] ([MSNV], [MSCV])
	VALUES (10, 1)

GO

--Table dbo.PHONGBAN

INSERT INTO [dbo].[PHONGBAN] ([MAPB], [TENPB])
	VALUES (1, N'Khoa Công nghệ thông tin')

GO
INSERT INTO [dbo].[PHONGBAN] ([MAPB], [TENPB])
	VALUES (2, N'Khoa Công nghệ sinh học')

GO
INSERT INTO [dbo].[PHONGBAN] ([MAPB], [TENPB])
	VALUES (3, N'Khoa Kiến trúc')

GO
INSERT INTO [dbo].[PHONGBAN] ([MAPB], [TENPB])
	VALUES (4, N'Khoa Công nghệ môi trường')

GO
INSERT INTO [dbo].[PHONGBAN] ([MAPB], [TENPB])
	VALUES (5, N'Khoa Ngoại ngữ')

GO

--Table dbo.PHUCAPCV


INSERT INTO [dbo].[PHUCAPCV] ([MSCV], [SOTIENPHUCAP])
	VALUES (1, 100000)

GO
INSERT INTO [dbo].[PHUCAPCV] ([MSCV], [SOTIENPHUCAP])
	VALUES (2, 50000)

GO
INSERT INTO [dbo].[PHUCAPCV] ([MSCV], [SOTIENPHUCAP])
	VALUES (3, 500000)

GO
INSERT INTO [dbo].[PHUCAPCV] ([MSCV], [SOTIENPHUCAP])
	VALUES (4, 600000)

GO
INSERT INTO [dbo].[PHUCAPCV] ([MSCV], [SOTIENPHUCAP])
	VALUES (5, 400000)

GO

--Table dbo.PHUCAPKHAC

INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (1, CAST(0xdf300b AS date), 100000, N'Sinh đẻ')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (1, CAST(0x02310b AS date), 350000, N'Tết')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (1, CAST(0x21310b AS date), 500000, N'Ngày quốc tế PN')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (1, CAST(0x56310b AS date), 400000, N'Ngày Giải phóng')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (2, CAST(0x02310b AS date), 500000, N'Tết')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (3, CAST(0x02310b AS date), 250000, N'Tết')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (3, CAST(0x56310b AS date), 250000, N'Ngày Giải phóng MN')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (4, CAST(0x02310b AS date), 500000, N'Tết')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (4, CAST(0x21310b AS date), 500000, N'Ngày Quốc tế PN')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (4, CAST(0x56310b AS date), 400000, N'Ngày Giải phóng MN')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (5, CAST(0x02310b AS date), 500000, N'Tết')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (5, CAST(0x56310b AS date), 400000, N'Ngày Giải phóng MN')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (6, CAST(0x02310b AS date), 500000, N'Tết')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (7, CAST(0x02310b AS date), 500000, N'Tết')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (7, CAST(0x21310b AS date), 450000, N'Ngày quốc tế PN')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (7, CAST(0x56310b AS date), 400000, N'Ngày Giải phóng MN')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (8, CAST(0x02310b AS date), 300000, N'Tết')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (8, CAST(0x56310b AS date), 400000, N'Ngày Giải phóng MN')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (9, CAST(0x02310b AS date), 500000, N'Tết')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (9, CAST(0x56310b AS date), 400000, N'Ngày Giải phóng MN')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (10, CAST(0x02310b AS date), 500000, N'Tết')

GO
INSERT INTO [dbo].[PHUCAPKHAC] ([MSNV], [NGAY], [SOTIEN], [LYDO])
	VALUES (10, CAST(0x21310b AS date), 500000, N'Ngày quốc tế PN')

GO

--Table dbo.TAMUNG

INSERT INTO [dbo].[TAMUNG] ([MSNV], [SOTIENCONTU], [SOTIENTRATHANG])
	VALUES (1, 4000000, 200000)

GO
INSERT INTO [dbo].[TAMUNG] ([MSNV], [SOTIENCONTU], [SOTIENTRATHANG])
	VALUES (2, 7000000, 100000)

GO
INSERT INTO [dbo].[TAMUNG] ([MSNV], [SOTIENCONTU], [SOTIENTRATHANG])
	VALUES (3, 0, 0)

GO
INSERT INTO [dbo].[TAMUNG] ([MSNV], [SOTIENCONTU], [SOTIENTRATHANG])
	VALUES (4, 10000000, 2500000)

GO
INSERT INTO [dbo].[TAMUNG] ([MSNV], [SOTIENCONTU], [SOTIENTRATHANG])
	VALUES (5, 0, 0)

GO
INSERT INTO [dbo].[TAMUNG] ([MSNV], [SOTIENCONTU], [SOTIENTRATHANG])
	VALUES (6, 1000000, 500000)

GO
INSERT INTO [dbo].[TAMUNG] ([MSNV], [SOTIENCONTU], [SOTIENTRATHANG])
	VALUES (7, 4600000, 200000)

GO
INSERT INTO [dbo].[TAMUNG] ([MSNV], [SOTIENCONTU], [SOTIENTRATHANG])
	VALUES (8, 0, 0)

GO
INSERT INTO [dbo].[TAMUNG] ([MSNV], [SOTIENCONTU], [SOTIENTRATHANG])
	VALUES (9, 200000, 100000)

GO
INSERT INTO [dbo].[TAMUNG] ([MSNV], [SOTIENCONTU], [SOTIENTRATHANG])
	VALUES (10, 1000000, 100000)

GO

--------------------------------
SELECT * FROM BANGCHAMCONG
SELECT * FROM LUONGTHANG
SELECT * FROM NHANVIEN
SELECT * FROM NV_CHUCVU
SELECT * FROM PHONGBAN
SELECT * FROM PHUCAPCV
SELECT * FROM PHUCAPKHAC
SELECT * FROM TAMUNG
---------------------------------------------------------------------------------