USE QUANLYDONHANG_B1_MSSV
---------------
DELETE DIEUKIENNHAPHANG
DELETE CHITIETDATHANG
DELETE DONDATHANG
DELETE NHANVIEN
DELETE KHACHHANG
DELETE MATHANG
DELETE NHACUNGCAP
DELETE LOAIHANG

---
DROP TABLE DIEUKIENNHAPHANG
DROP TABLE CHITIETDATHANG
DROP TABLE DONDATHANG
DROP TABLE NHANVIEN
DROP TABLE KHACHHANG
DROP TABLE MATHANG
DROP TABLE NHACUNGCAP
DROP TABLE LOAIHANG
---
DROP DATABASE QUANLYDONHANG_B1_MSSV